config/routes.rb
require 'heartbeat/application'

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root 'application#index'
    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      patch :archive, on: :member
    end
    resources :states, only: [:index, :new, :create] do
      member do
        patch :make_default
      end
    end
  end

  namespace :api do
    namespace :v2 do
      mount API::V2::Tickets, at: "/projects/:project_id/tickets"
    end

    scope path: "/projects/:project_id", as: "project" do
      resources :tickets
    end
  end

  resources :attachments, only: [:show]

  resources :projects, except: [:new, :create, :destroy] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove  
      end
    end
  end

  devise_for :users

  root 'projects#index'
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tickets, dependent: :destroy do
    def search(params)
      # If search query match pattern of e.g. 'tag:new'.
      if params =~ /\A\w+:\w+\z/
        attribute = params.match(/\A(\w+):/)[1].pluralize.to_sym
        value = params.match(/:(\w+)\z/)[1]
        joins(attribute).where("#{attribute}.name = '#{value}'")
      else
        # Return the whole collection otherwise.
        return self
      end
    end
  end
  has_many :roles, dependent: :delete_all
  validates :name, presence: true, length: { minimum: 3 }

  # Some helper methods for Pundit policies.
  def has_member?(user)
    roles.exists?(user_id: user)
  end

  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project has been created.'
    else
      flash.now[:alert] = 'Project has not been created.'
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])

    @project.destroy

    redirect_to projects_url, notice: 'Project has been deleted.'
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_project

  def index
    @projects = policy_scope(Project)
  end

  def show
    authorize @project, :show?
    @tickets = @project.tickets
  end

  def edit
    authorize @project, :update?
  end

  def update
    authorize @project, :update?
    if @project.update(project_params)
      redirect_to @project, notice: 'Project has been updated.'
    else
      flash.now[:alert] = 'Project has not been updated.'
      render :edit
    end
  end

  private

    def set_project
      @project = Project.find(params[:id])
    end

    def invalid_project
      logger.error "Attempt to access invalid project -> #{params[:id]}"
      redirect_to projects_url,
        alert: 'The project you were looking for could not be found.'
    end

    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def state_transition_for(comment)
    if comment.previous_state != comment.state
      content_tag(:p) do
        value = "<strong><i class='fa fa-gear'></i> state changed</strong>"
        if comment.previous_state.present?
          value += " from #{render comment.previous_state}"
        end
        value += " to #{render comment.state}"
        value.html_safe
      end
    end
  end
end

app/views/projects/_form.html.haml
= simple_form_for project do |f|
  = f.input :name
  = f.input :description

  = f.button :submit, class: 'btn-primary'

app/views/projects/edit.html.haml
%header
  %h1 Edit Project
= render 'form', project: @project

app/views/projects/index.html.haml
%header
  %h1 Projects
  - admins_only do
    %ul.actions
      %li= link_to 'New Project', new_admin_project_path, class: 'new'

#projects
  - @projects.each do |project|
    %h2= link_to project.name, project
    %p= project.description

app/views/projects/show.html.haml
- title @project.name, 'Projects'

%header
  %h1= @project.name
  %ul.actions
    - if policy(@project).update?
      %li= link_to 'Edit Project', edit_project_path(@project), class: 'edit'
    - admins_only do
      %li= link_to 'Delete Project', admin_project_path(@project),
              method: :delete,
              class: 'delete',
              data: { confirm: 'Are you sure you want to delete this project?' }
            
%p= @project.description

%header
  %h2 Tickets
  
  %ul.actions
    %li
      = form_tag search_project_tickets_path(@project), method: :get,
        class: 'form-inline' do
        = label_tag 'search', 'Search', class: 'sr-only'
        = text_field_tag 'search', params[:search], placeholder: 'tag:important',
          class: 'form-control'
        = submit_tag 'Search', class: 'btn btn-default'
    - if policy(Ticket.new(project: @project)).create?
      %li= link_to 'New Ticket', new_project_ticket_path(@project), class: 'new'

%ul#tickets
  - @tickets.each_with_index do |ticket, idx|
    %li
      \##{idx + 1} -
      = link_to ticket.name, [@project, ticket]
      = render ticket.state if ticket.state