config/routes.rb
require 'heartbeat/application'

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root 'application#index'
    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      patch :archive, on: :member
    end
    resources :states, only: [:index, :new, :create] do
      member do
        patch :make_default
      end
    end
  end

  namespace :api do
    namespace :v2 do
      mount API::V2::Tickets, at: "/projects/:project_id/tickets"
    end

    scope path: "/projects/:project_id", as: "project" do
      resources :tickets
    end
  end

  resources :attachments, only: [:show]

  resources :projects, except: [:new, :create, :destroy] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove  
      end
    end
  end

  devise_for :users

  root 'projects#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :roles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :not_archived, -> { where(archived_at: nil) }

  def generate_api_key
    self.update_column(:api_key, SecureRandom.hex(16))
  end

  def to_s
    "#{email} (#{admin? ? 'Admin' : 'User'})"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  # Overwrite Devise's default method.
  def active_for_authentication?
    super && archived_at.nil?
  end

  # Another Devise's overwrite.
  def inactive_message
    archived_at.nil? ? super : :archived
  end

  def role_on(project)
    roles.find_by(project_id: project).try(:name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_projects, only: [:new, :edit, :create, :update]
  before_action :set_user, only: [:show, :edit, :update, :archive]

  def index
    @users = User.not_archived
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    build_roles_for(@user)

    if @user.save
      redirect_to admin_users_path, notice: 'User has been created.'
    else
      flash.now[:alert] = 'User has not been created.'
      render :new
    end
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    User.transaction do
      @user.roles.clear
      build_roles_for(@user)

      if @user.update(user_params)
        redirect_to admin_users_path, notice: 'User has been updated.'
      else
        flash.now[:alert] = 'User has not been updated.'
        render :edit
        raise ActiveRecord::Rollback
      end
    end
  end

  def archive
    if @user == current_user
      flash[:alert] = 'You cannot archive yourself!'
    else
      @user.archive
      flash[:notice] = "User has been archived."
    end

    redirect_to admin_users_path
  end

  private

    def build_roles_for(user)
      role_data = params.fetch(:roles, [])
      role_data.each do |project_id, role_name|
        if role_name.present?
          user.roles.build(project_id: project_id, role: role_name)
        end
      end
    end

    def set_user
      @user = User.find(params[:id])
    end

    def set_projects
      @projects = Project.order(:name)
    end

    def user_params
      params.require(:user).permit(:email, :password, :admin)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.haml
= simple_form_for [:admin, user] do |f|
  = f.input :email
  = f.input :password
  = f.input :admin, label: "Is an admin?"

  %header
    %h2 Roles
  %table.roles
    - projects.each do |project|
      %tr
        %th= label_tag dom_id(project), project.name
        %td
          = select_tag dom_id(project), options_for_select(roles,
            user.role_on(project)), name: "roles[#{project.id}]",
            include_blank: true

  = f.button :submit, class: 'btn btn-primary'

app/views/admin/users/edit.html.haml
%header
  %h1 Edit User

= render 'form', user: @user, projects: @projects

app/views/admin/users/index.html.haml
%header
  %h1 Users
  %ul.actions
    %li= link_to 'New User', new_admin_user_path, class: 'new'

%ul
  - @users.each do |user|
    %li= link_to user, [:admin, user]

app/views/admin/users/new.html.haml
%header
  %h1 New User

= render 'form', user: @user, projects: @projects

app/views/admin/users/show.html.haml
%header
  %h1= @user

  %ul.actions
    %li
      = link_to 'Edit User', [:edit, :admin, @user], class: 'edit'
      = link_to 'Archive User', [:archive, :admin, @user], method: :patch,
          class: 'delete',
          data: { confirm: 'Do you really want to archive this user?'}

%header
  %h2 Roles

- if @user.roles.any?
  %ul
    - @user.roles.each do |role|
      %li
        = role.project.name + ':'
        = role.role.titleize
- else
  %p This user has no roles