config/routes.rb
require 'heartbeat/application'

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root 'application#index'
    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      patch :archive, on: :member
    end
    resources :states, only: [:index, :new, :create] do
      member do
        patch :make_default
      end
    end
  end

  namespace :api do
    namespace :v2 do
      mount API::V2::Tickets, at: "/projects/:project_id/tickets"
    end

    scope path: "/projects/:project_id", as: "project" do
      resources :tickets
    end
  end

  resources :attachments, only: [:show]

  resources :projects, except: [:new, :create, :destroy] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove  
      end
    end
  end

  devise_for :users

  root 'projects#index'
end

app/models/state.rb
class State < ApplicationRecord
  def self.default
    find_by(default: true)
  end

  def to_s
    name
  end

  def make_default!
    State.update_all(default: false)
    update!(default: true)
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::ApplicationController
  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
    if @state.save
      redirect_to admin_states_path, notice: "State has been created."
    else
      flash.now[:alert] = "State has not been created."
      render :new
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.make_default!

    flash[:notice] = "'#{@state.name}' is now the default state."
    redirect_to admin_states_url
  end

  private

    def state_params
      params.require(:state).permit(:name, :color)
    end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.haml
= simple_form_for [:admin, state] do |f|
  = f.input :name
  = f.input :color
  
  = f.submit class: 'btn btn-primary'

app/views/admin/states/index.html.haml
%header
  %h1 States

  %ul.actions
    %li= link_to 'New State', new_admin_state_path, class: 'new'

%ul#states
  - @states.each do |state|
    %li
      = render 'states/state', state: state
      - if state.default?
        (Default)
      - else
        = link_to "Make Default", make_default_admin_state_path(state),
          method: :patch

app/views/admin/states/new.html.haml
%header
  %h1 New State

= render "form", state: @state